[theme]

# Primary accent for interactive elements
primaryColor = '#00172B'

# Background color for the main content area
backgroundColor = '#0a0a0a'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#191919'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"